<?php
/**
 *  SeekQuarry/Yioop --
 *  Open Source Pure PHP Search Engine, Crawler, and Indexer
 *
 *  Copyright (C) 2013  Chris Pollett chris@pollett.org
 *
 *  LICENSE:
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  END LICENSE
 *
 * @author Chris Pollett chris@pollett.org
 * @package seek_quarry
 * @subpackage indexing_plugin
 * @license http://www.gnu.org/licenses/ GPL3
 * @link http://www.seekquarry.com/
 * @copyright 2009 - 2013
 * @filesource
 */

if(!defined('BASE_DIR')) {echo "BAD REQUEST"; exit();}

/** Loads processor used for */
require_once BASE_DIR."/lib/processors/text_processor.php";
/** Base indexing plugin class*/
require_once BASE_DIR."/lib/indexing_plugins/indexing_plugin.php";
/** Get the crawlHash function */
require_once BASE_DIR."/lib/utility.php";
/** Loads common constants for web crawling */
require_once BASE_DIR."/lib/crawl_constants.php";

/**
 * IndexingPlugin is used to filter documents by term during a crawl.
 *
 * When this plugin is in use, each document summary that is generated by a
 * TextProcessor or subclass during a crawl will be further processed by it
 * pageSummaryProcessing method. As part of this
 * processing the summary's title and description are sent to
 * the method checkFilter. Here they are compared against the associative array
 * $this->filter_terms which consists of a list of term => array of actions
 * pairs. Actions can either be directives that might appear within a ROBOTS
 * meta tag of an HTML document: NOINDEX, NOFOLLOW, NOCACHE, NOARCHIVE, NOODP,
 * NOYDIR, NONE or can be the word NOPROCESS, JUSTFOLLOW, NOTCONTAINS. 
 * Usually, if checkFilter returns true then pageSummaryProcessing adds the 
 * meta words to the document summary and returns. If one of the actions
 * was NOTCONTAIN, then only if checkFilter returned false are the meta words
 * added. The crawl makes use of the meta word info when performing indexing.
 * In the case where the actions contain NOPROCESS the summary returned from
 * pageSummaryProcessing will be false this will prevent any indexing of this
 * document from occuring at all. In the case where the actions contain
 * JUSTFOLLOW, the document won't be stored in the index but links from it will
 * be followed.
 *
 * This plugin has been created with a dummy list of filter words. By doing a
 * crawl on the test site contain in the archive
 *      tests/word-filter-test-crawl.zip
 * one can  test how it behaves on those terms. If one wants to make use of
 * this plugin on real web data one probably wants to create a subclass of this
 * plugin in WORK_DIRECTORY/app/lib/indexing_plugins where one has a different
 * array of filter_terms. To get a more sophisticated filtering process than a
 * mere word-in-document-true-or-false check one would override checkFilter.
 * One can also directly modify the code below to achieve these effects, but
 * altering code under the BASE_DIR makes it slightly harder to newer versions
 * Yioop as they come out.
 *
 * @author Chris Pollett
 * @package seek_quarry
 * @subpackage indexing_plugin
 */
class WordfilterPlugin extends IndexingPlugin implements CrawlConstants
{
    /**
     * Associative array of term => actions pairs, where term is a word to
     * check against the filter and actions is an array of actions from
     * among: NOINDEX, NOFOLLOW, NOCACHE, NOARCHIVE, NOODP, NOYDIR, NONE,
     *    NOTCONTAIN, JUSTFOLLOW, and NOPROCESS.
     *
     * @var array
     */
    var $filter_terms = array(
        "term0" => array("NOTCONTAIN", "JUSTFOLLOW"),
        "term1" => array("NOPROCESS"),
        "term2" => array("NOFOLLOW", "NOSNIPPET")
    );
    /**
     * This method adds robots metas to or removes entirely a summary
     * produced by a text page processor or its subsclasses depending on
     * whether the summary title and description contain one of the terms
     * listed in $this->filter_times.
     *
     * @param array &$summary the summary data produced by the relevant page
     *      processor's handle method; modified in-place.
     */
    function pageSummaryProcessing(&$summary)
    {
        foreach ($this->filter_terms as $term => $actions) {
            $filter_flag = $this->checkFilter($term, $summary[self::TITLE],
                $summary[self::DESCRIPTION]);
            if(in_array("NOTCONTAIN", $actions)) {
                $filter_flag = ($filter_flag) ? false : true;
                $actions = array_values(array_diff($actions,
                    array("NOTCONTAIN")));
            }
            if($filter_flag) {
                if(in_array("NOPROCESS", $actions)) {
                    crawlLog("  Word filter plugin removed page.");
                    $summary = false;
                    break;
                } else {
                    if(!isset($summary[self::ROBOT_METAS])) {
                        $summary[self::ROBOT_METAS] = array();
                    }
                    $summary[self::ROBOT_METAS] += $actions;
                }
            }
        }
    }

    /**
     * Used to check if the $term occurence in the $title and $description
     * meets a criteria under which it should be filtered.
     *
     * For this version of checkFilter we are only checking whether the term
     * appears in the title or description
     *
     * @param string $term the word or string to search for
     * @param string $title of a web page summary
     * @param string $description of a web page summary
     * @return bool whether the summary should be filtered or not
     */
    function checkFilter($term, $title, $description)
    {
        $title_description = $title." ".$description;
        if(strpos($title_description, $term) !== false) {
            return true;
        }
        return false;
    }

    /**
     * Which mime type page processors this plugin should do additional
     * processing for
     *
     * @return array an array of page processors
     */
    static function getProcessors()
    {
        return array("TextProcessor"); //will apply to all subclasses
    }

}

?>
